MAKEFLAGS += --silent
C_BLU='\033[0;34m'
C_GRN='\033[0;32m'
C_RED='\033[0;31m'
C_YEL='\033[0;33m'
C_END='\033[0m'

REPO_URL=https://github.com/(your-github-user)/(your-repository-name).git
REPO_SSH=git@github.com:(your-github-user)/(your-repository-name).git
REPO_MAIN=master

help: ## Show this help message
	echo 'usage: make [target]'
	echo
	echo 'targets:'
	egrep '^(.+)\:\ ##\ (.+)' ${MAKEFILE_LIST} | column -t -c 2 -s ':#'

# Common git process

repo-info: ## Commits the HEAD of remote git repository branch.
	@echo "Repository URL:" ${C_YEL}$(shell git config --get remote.origin.url)${C_END}

# Specific branch $ make repo-update branch=??? comment="???"
# Or by default master branch $ make repo-update
# Check git configurations before use this script, like: $ git remote -v
branch ?= master
comment ?= main/$(shell date +"%Y%m%d%H%M%S")
repo-commit: ## Commits the HEAD of remote git repository branch.
	@echo ${C_YEL}"ATTENTION:"${C_END}
	@echo "All local changes from branch:"
	git branch;
	@echo "Is going to be pushed into * "${C_YEL}"$(branch)"${C_END}" branch,"
	@echo "On repository" ${C_YEL}$(shell git config --get remote.origin.url)${C_END}
	@echo "with the following commit comment:"
	@echo "*" ${C_GRN}${comment}${C_END};
	@echo -n ${C_YEL}"Are you sure? "${C_END}"[Y/n]" && read ans && if [ $${ans:-'Y'} = 'n' ]; then \
        echo ${C_RED}"K.O.! process has been stopped."${C_END}; \
    else \
		git stash; \
		git pull origin master; \
		git stash pop; \
		git add .; \
		git commit -m "$(comment)"; \
		git push origin -u master; \
        echo ${C_GRN}"O.K.! process has been finished."${C_END}; \
    fi

repo-install: ## Install git repository when remote is empty.
	git init;
	git remote add origin ${REPO_SSH};
	git branch -M ${REPO_MAIN};

repo-create: ## Creates git repository on local and remote.
	echo "# localadmin" >> README.md;
	git init;
	git add README.md;
	git commit -m "first commit";
	git branch -M ${REPO_MAIN};
	git remote add origin ${REPO_SSH};
	git push -u origin ${REPO_MAIN};